# Posture manifest schema (planning)
# Fields: id, name, category, pretext, human_factor, drift_change, assumed_access,
# mapped_kill_chain (phase, technique, scripts, telemetry), expected_wazuh_alerts,
# detection_notes, runner_parameters.

id: "01"                               # string, unique
name: "Reduced MFA coverage"           # posture title
category: "Social Engineering Drift"
pretext: "Urgent executive travel / SSO outage"
human_factor: "Authority + urgency"
drift_change:
  description: "MFA disabled/bypassed for subset of users/apps"
  scope: ["user:<id>", "app:<id>"]
assumed_access:
  credentials: "Valid creds without MFA"
  network: "SSO/VPN reachability"
mapped_kill_chain:
  - phase: "Initial Access"
    technique: "Valid Accounts (T1078)"
    scripts: ["initial_access_valid_creds.py"]
    telemetry:
      - "auth.log: login success without MFA field"
  - phase: "Execution"
    technique: "Command Execution (T1059)"
    scripts: ["exec_follow_on.py"]
    telemetry:
      - "process: /bin/sh -c 'echo ...'"
  - phase: "Persistence"
    technique: "Scheduled Task/Job (T1053)"
    scripts: ["persistence_temp_cron.py"]
    telemetry:
      - "file: /tmp/purple-lab-cron"
  - phase: "Command and Control"
    technique: "Application Layer Protocol: Web (T1071.001)"
    scripts: ["c2_http_localhost.py"]
    telemetry:
      - "network: curl http://localhost:8080/beacon"
expected_wazuh_alerts:
  - name: "Auth success without MFA"
    rule_id: "TODO-MFA-BYPASS"
    evidence: ["auth.log entry missing MFA claim"]
  - name: "Temp cron creation"
    rule_id: "TODO-CRON-TMP"
    evidence: ["/tmp/purple-lab-cron"]
  - name: "HTTP beacon"
    rule_id: "TODO-HTTP-BEACON"
    evidence: ["curl to localhost:8080/beacon"]
detection_notes:
  false_positive_considerations:
    - "Break-glass accounts"
    - "Maintenance windows"
  tuning:
    - "Scope by test user/app and time window"
runner_parameters:
  timeout_seconds: 180
  artifacts_path: "/tmp/purple-lab-artifacts"
  log_level: "info"
